export const CREATE_AN_ADVERTISEMENT_REQUEST = "CREATE_AN_ADVERTISEMENT_REQUEST";
export const CREATE_AN_ADVERTISEMENT_SUCCESS = "CREATE_AN_ADVERTISEMENT_SUCCESS";
export const CREATE_AN_ADVERTISEMENT_FAILURE = "CREATE_AN_ADVERTISEMENT_FAILURE";

export const GET_ALL_ADVERTISEMENT_REQUEST = "GET_ALL_ADVERTISEMENT_REQUEST";
export const GET_ALL_ADVERTISEMENT_SUCCESS = "GET_ALL_ADVERTISEMENT_SUCCESS";
export const GET_ALL_ADVERTISEMENT_FAILURE = "GET_ALL_ADVERTISEMENT_FAILURE";

export const DELETE_ADVERTISEMENT_REQUEST = "DELETE_ADVERTISEMENT_REQUEST";
export const DELETE_ADVERTISEMENT_SUCCESS = "DELETE_ADVERTISEMENT_SUCCESS";
export const DELETE_ADVERTISEMENT_FAILURE = "DELETE_ADVERTISEMENT_FAILURE";

export const UPDATE_ADVERTISEMENT_REQUEST = "UPDATE_ADVERTISEMENT_REQUEST";
export const UPDATE_ADVERTISEMENT_SUCCESS = "UPDATE_ADVERTISEMENT_SUCCESS";
export const UPDATE_ADVERTISEMENT_FAILURE = "UPDATE_ADVERTISEMENT_FAILURE";

export const GET_ADVERTISEMENT_BY_USER_ID_REQUEST = "GET_ADVERTISEMENT_BY_USER_ID_REQUEST";
export const GET_ADVERTISEMENT_BY_USER_ID_SUCCESS = "GET_ADVERTISEMENT_BY_USER_ID_SUCCESS";
export const GET_ADVERTISEMENT_BY_USER_ID_FAILURE = "GET_ADVERTISEMENT_BY_USER_ID_FAILURE";

export const UPDATE_ADVERTISEMENT_STATUS_REQUEST = "UPDATE_ADVERTISEMENT_STATUS_REQUEST";
export const UPDATE_ADVERTISEMENT_STATUS_SUCCESS = "UPDATE_ADVERTISEMENT_STATUS_SUCCESS";
export const UPDATE_ADVERTISEMENT_STATUS_FAILURE = "UPDATE_ADVERTISEMENT_STATUS_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const GET_ADVERTISEMENT_BY_ID_REQUEST = "GET_ADVERTISEMENT_BY_ID_REQUEST";
export const GET_ADVERTISEMENT_BY_ID_SUCCESS = "GET_ADVERTISEMENT_BY_ID_SUCCESS";
export const GET_ADVERTISEMENT_BY_ID_FAILURE = "GET_ADVERTISEMENT_BY_ID_FAILURE";